export const typography = {
  fontFamily: {
    regular: 'System',
    medium: 'System',
    semiBold: 'System',
    bold: 'System',
  },
  fontSize: {
    xs: 12,
    sm: 14,
    base: 16,
    lg: 18,
    xl: 20,
    '2xl': 24,
    '3xl': 30,
    '4xl': 36,
  },
  lineHeight: {
    xs: 16,
    sm: 20,
    base: 24,
    lg: 28,
    xl: 28,
    '2xl': 32,
    '3xl': 36,
    '4xl': 40,
  },
  fontWeight: {
    regular: '400' as const,
    medium: '500' as const,
    semiBold: '600' as const,
    bold: '700' as const,
  },
  h1: { fontSize: 36, lineHeight: 40, fontWeight: '700' as const, fontFamily: 'System' },
  h2: { fontSize: 30, lineHeight: 36, fontWeight: '700' as const, fontFamily: 'System' },
  h3: { fontSize: 24, lineHeight: 32, fontWeight: '700' as const, fontFamily: 'System' },
  h4: { fontSize: 20, lineHeight: 28, fontWeight: '600' as const, fontFamily: 'System' },
  h5: { fontSize: 18, lineHeight: 28, fontWeight: '600' as const, fontFamily: 'System' },
  h6: { fontSize: 16, lineHeight: 24, fontWeight: '600' as const, fontFamily: 'System' },
  subtitle1: { fontSize: 16, lineHeight: 24, fontWeight: '500' as const, fontFamily: 'System' },
  subtitle2: { fontSize: 14, lineHeight: 20, fontWeight: '500' as const, fontFamily: 'System' },
  body1: { fontSize: 16, lineHeight: 24, fontWeight: '400' as const, fontFamily: 'System' },
  body2: { fontSize: 14, lineHeight: 20, fontWeight: '400' as const, fontFamily: 'System' },
  button: { fontSize: 14, lineHeight: 20, fontWeight: '600' as const, fontFamily: 'System' },
  caption: { fontSize: 12, lineHeight: 16, fontWeight: '400' as const, fontFamily: 'System' },
  overline: { fontSize: 10, lineHeight: 16, fontWeight: '600' as const, fontFamily: 'System', textTransform: 'uppercase' as const },
} as const;
