export const designTokens = {
  colors: {
    primary: '#FF5C8A',
    primaryGold: '#FF5C8A',
    dark: '#0F0F0F',
    gray: '#4F4F4F',
    white: '#0F172A',
    glass: 'rgba(255,255,255,0.12)',
    glassBorder: 'rgba(255,255,255,0.2)',
    textLight: '#BDBDBD',
    textMuted: '#9E9E9E',
    textSubtle: '#D0D0D0',
    iconGray: '#7A7A7A',
    overlay: 'rgba(0,0,0,0.65)',
    overlayDark: 'rgba(0,0,0,0.45)',
    overlayGradientTop: 'rgba(0,0,0,0.25)',
    overlayGradientBottom: 'rgba(0,0,0,0.85)',
  },
  typography: {
    fontFamily: {
      heading: 'Playfair Display',
      body: 'Poppins',
    },
    sizes: {
      logo: 42,
      heading: 30,
      tagline: 15,
      label: 13,
      input: 15,
      caption: 12,
      button: 16,
      divider: 13,
    },
    weights: {
      regular: '400' as const,
      medium: '500' as const,
      semibold: '600' as const,
      bold: '700' as const,
    },
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 14,
    md: 24,
    lg: 32,
  },
  shadows: {
    logo: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 15,
      elevation: 8,
    },
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -10 },
      shadowOpacity: 0.35,
      shadowRadius: 40,
      elevation: 20,
    },
    button: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 24,
      elevation: 12,
    },
    social: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 15,
      elevation: 6,
    },
  },
  animations: {
    fade: 800,
    logoFadeIn: 800,
    backgroundZoom: 15000,
    buttonPress: 120,
    press: 120,
  },
} as const;
